pipeline {
    agent any

    tools {
        maven 'MAVEN_HOME'   // Make sure this name matches your Jenkins Maven installation
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/JlassiHoussem/nopeCommerce_SelenuimAutomation.git'
            }
        }

        stage('Run Regression Suite') {
            steps {
                // Run only the regression.xml suite
                bat """ "${tool 'MAVEN_HOME'}/bin/mvn" clean test -DsuiteXmlFile=regression.xml """
            }
        }

        stage('Results') {
            steps {
                // Collect TestNG results generated by Surefire
                junit '**/target/surefire-reports/TEST-*.xml'
                archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
            }
        }
    }

    post {
        success {
            echo "✅ Regression suite executed successfully!"
        }
        failure {
            echo "❌ Regression suite failed!"
        }
    }
}
